"""Smoke 2B — Provenance: evidence.item_ids non-empty after mini P1 + cluster + synth.

Pass criteria:
  - p1_extractions has item_id as first-class field for every record.
  - After cluster + synth, evidence.item_ids is non-empty for ALL eligible units.
  - Zero units with evidence.item_ids == [].

Uses a pre-existing p1_extractions.jsonl (must have been generated by smoke 2D or full run).
If not present, runs a mini P1 extraction for up to 20 users.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
P1_PATH = ROOT / "data/processed/Books/p1_extractions.jsonl"
SPLITS_PATH = ROOT / "data/processed/Books/splits.json"


def run_mini_extraction(n_users: int = 20, output_dir: str = "data/p1_shards_smoke2b") -> str:
    """Run a mini parallel extraction → return path to p1_extractions.jsonl."""
    cmd = (
        f"python3 scripts/parallel_memory_build.py "
        f"--category Books --variant B "
        f"--n_workers 1 --max_users_per_worker {n_users} "
        f"--output_dir {output_dir} "
        f"--report_dir reports"
    )
    print(f"[2B] Running mini extraction: {cmd}")
    ret = os.system(cmd)
    if ret != 0:
        sys.exit(f"[FAIL] Mini extraction failed (exit {ret})")
    return str(ROOT / "data/processed/Books/p1_extractions.jsonl")


def run_mini_cluster_synth(p1_records: list[dict]) -> list[dict]:
    """Cluster + synth subset of p1_records; return flat list of units."""
    from src.memory.cluster import (
        _centroid, _keyword_union, _medoid_idx,
        _extract_pref_summary, _agglomerative_labels,
    )
    from src.memory.synth import make_memory_id, make_intent_memory_unit
    from src.memory.embed import EmbeddingModel
    from collections import defaultdict

    TAU = 0.30
    K_MAX = 5

    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[2B] Loading EmbeddingModel on {device} ...")
    emb_model = EmbeddingModel(device=device)

    user_groups: dict = defaultdict(list)
    for r in p1_records:
        user_groups[r["user_id"]].append(r)

    all_units = []
    for uid, reviews in list(user_groups.items())[:20]:
        eligible = [r for r in reviews if r.get("eligible", False)]
        if not eligible:
            continue

        source_texts = [r.get("source_text") or r.get("review_text", "") for r in eligible]
        intents = [r.get("contextual_intent", "") for r in eligible]
        item_ids = [r.get("item_id") for r in eligible]
        timestamps = [r.get("timestamp") for r in eligible]
        evidence_spans = [r.get("evidence_span", "") for r in eligible]

        vecs = emb_model.encode_corpus(source_texts)
        n = len(eligible)
        raw_labels = [0] if n == 1 else _agglomerative_labels(vecs, TAU, 1, 5)
        labels = raw_labels
        n_clusters = int(max(labels)) + 1 if labels else 0

        for cl in range(n_clusters):
            member_indices = [i for i, lb in enumerate(labels) if lb == cl]
            if not member_indices:
                continue
            embs = vecs[member_indices]
            med_local = _medoid_idx(embs)
            med_global = member_indices[med_local]
            pref_summaries = [
                _extract_pref_summary(source_texts[i], intents[i])
                for i in member_indices
            ]
            cluster = {
                "label": cl,
                "size": len(member_indices),
                "source_texts": [source_texts[i] for i in member_indices],
                "intents": [intents[i] for i in member_indices],
                "pref_summaries": pref_summaries,
                "embeddings": embs,
                "centroid": _centroid(embs),
                "medoid_local_idx": med_local,
                "medoid_intent": intents[med_global],
                "medoid_source_text": source_texts[med_global],
                "keyword_union": _keyword_union(pref_summaries),
            }
            ev_item_ids = [item_ids[i] for i in member_indices]
            ev_timestamps = [timestamps[i] for i in member_indices]
            ev_snippets = [evidence_spans[i] for i in member_indices]

            mid = make_memory_id(uid, cl, TAU)
            unit = make_intent_memory_unit(
                memory_id=mid,
                user_id=uid,
                cluster={**cluster, "_k_personal": n_clusters},
                tau=TAU,
                is_prototype=False,
                evidence_item_ids=ev_item_ids,
                evidence_timestamps=ev_timestamps,
                evidence_snippets=ev_snippets,
            )
            all_units.append(unit)

    return all_units


def main() -> None:
    print("=" * 60)
    print("SMOKE 2B — Provenance: evidence.item_ids non-empty")
    print("=" * 60)

    # Check p1 records exist
    if not P1_PATH.exists():
        print(f"[2B] p1_extractions.jsonl not found — running mini extraction ...")
        run_mini_extraction(n_users=20)

    if not P1_PATH.exists():
        sys.exit(f"[FAIL] p1_extractions.jsonl still not found: {P1_PATH}")

    with open(P1_PATH, encoding="utf-8") as f:
        p1_records = [json.loads(l) for l in f if l.strip()]

    print(f"[2B] Loaded {len(p1_records)} P1 records")

    # Check 1: item_id is first-class field in every record
    missing_item_id = [i for i, r in enumerate(p1_records) if not r.get("item_id")]
    if missing_item_id:
        print(f"[FAIL] {len(missing_item_id)} records missing item_id. e.g. rows {missing_item_id[:5]}")
        sys.exit(1)
    print(f"[2B] item_id present in all {len(p1_records)} records ✓")

    # Check 2: Run mini cluster + synth → evidence.item_ids non-empty
    print(f"[2B] Running mini cluster+synth on up to 20 users ...")
    units = run_mini_cluster_synth(p1_records)

    n_empty_evidence = sum(1 for u in units if not u.get("evidence", {}).get("item_ids"))
    n_total = len(units)

    print(f"[2B] Units generated: {n_total}")
    print(f"[2B] Units with empty evidence.item_ids: {n_empty_evidence}")

    if n_total == 0:
        print(f"[FAIL] No units generated — no eligible reviews in P1 records?")
        sys.exit(1)

    if n_empty_evidence > 0:
        samples = [u for u in units if not u.get("evidence", {}).get("item_ids")][:3]
        for s in samples:
            print(f"  empty evidence: user={s['user_id']} memory_id={s['memory_id']}")
        print(f"\n[FAIL] 2B — {n_empty_evidence}/{n_total} units have empty evidence.item_ids!")
        sys.exit(1)

    print(f"\n[PASS] 2B — All {n_total} units have non-empty evidence.item_ids.")


if __name__ == "__main__":
    main()
